apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mar11-testragnew-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar11-testragnew-1
  name: mar11-testragnew-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
